# Numpy

#### Importing NUMPY

In [2]:
import numpy as np

#### Creating one directional array

In [6]:
my_list=[1,2,3,4]

a=np.array(my_list) # a is an one dimentional array """ Defining an Array"""

print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.shape) # array_name.shape gives us the number of rows and colums in the array and tell us the dimentions of the array

(4,)


In [9]:
print(a)

[1 2 3 4]


#### Creating two-directional array

In [10]:
my_list2=[4,5,6,7]
my_list3=[4,9,7,3]

b=np.array([my_list,my_list2,my_list3])# This is an 2 dimentional array

print(b)

[[1 2 3 4]
 [4 5 6 7]
 [4 9 7 3]]


In [11]:
print(b.shape)# array_name.shape gives use the number of rows and colums in the array and tell us the dimentions of the array

(3, 4)


##### Reshaping the two dimentional array

In [12]:
print(b.reshape(4,3)) #  array_name.reshape use to reshape the array ""THe number of element before and after the reshaping should be same


[[1 2 3]
 [4 4 5]
 [6 7 4]
 [9 7 3]]


#### Indexing

##### One-dimentional indexting

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [15]:
print(arr[2])# this is one dimenstional indexing

3


##### Two-dimentional indexing

In [16]:
ar=np.array([[1,2,3,4,5,6,7,8,9],
            [2,4,6,7,7,3,2,3,2],
            [3,4,5,3,4,5,4,2,4]])

print(ar)

[[1 2 3 4 5 6 7 8 9]
 [2 4 6 7 7 3 2 3 2]
 [3 4 5 3 4 5 4 2 4]]


In [18]:
print(ar[0:4,0:3]) # THis is two dimentional indexting '''[includs:includes+1,include,include+1]'''


[[1 2 3]
 [2 4 6]
 [3 4 5]]


#### Arrange

In [19]:
ap=np.arange(0,10, step=2) # Its an inbuild  function in numpy that create an array with specific progration
print(ap)

[0 2 4 6 8]


#### Linspace

In [20]:
app=np.linspace(1,10,10)# this in-build funtion create an array from start point to an end point and and divide it into equally space points
print(app)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### Copy funtion and Broadcasting function

In [21]:
app[3:]=2 # This will replace the items from the array

print(app)
 
new=app.copy()# by copying  by copy function the old array will not be affacted by changing the new array

new[0:]=5 #Know by changing in this array the old array will not be affacted

print(new)

[1. 2. 3. 2. 2. 2. 2. 2. 2. 2.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Some condtion very usful in exploratory data analysis

In [22]:
var=2
print(new>2)# This compair each element of new with var

[ True  True  True  True  True  True  True  True  True  True]


#### Creating array and reshaping it

In [23]:
new_array=np.arange(0,20,2).reshape(5,2)

print(new_array)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


#### Ones function

In [25]:
new_2=np.ones((4,5),dtype=int) #this create arrays of "1" in any shape
print(new_2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


####  Random function

In [26]:
new_3=np.random.rand(2,3) #this create arrays of random integers in any shape
print(new_3)

[[0.29925125 0.15467104 0.59266368]
 [0.26715641 0.3632034  0.81251008]]


#### Specific Random function 

In [27]:
new_4=np.random.randint(0,100,10)#this create arrays of random integers between any interval and number of intergers are also given in any shape

print(new_4)

[51 79 18 49 94 48 39 98 42 45]
